name: Template teste
description: Testes leitura de arquivos e matrizes.
title: Teste
labels: ["Teste"]
body:
  - type: input
    id: Area
    attributes:
      label: ">>Area<<"
      description: Uma area qualquer de uma empresa.
    validations:
      required: true
  - type: input
    id: Tipo
    attributes:
      label: ">>Tipo<<"
      description: Tipo online ou batch.
    validations:
      required: true
