name: "Extract configure information for area"

inputs:
  area:
    required: true

outputs:
  area: 
    value: ${{ steps.extract.outputs.area }}
  zonas_online:
    value: ${{ steps.extract.outputs.zonas_online }}
  zonas_batch:
    value: ${{ steps.extract.outputs.zonas_batch }}
  funcionalidades:
    value: ${{ steps.extract.outputs.funcionalidades }}
  excecoes:
    value: ${{ steps.extract.outputs.excecoes }}

runs:

  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract configure information
      id: extract
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x extract-config-info.sh
        ./extract-config-info.sh "${{ inputs.area }}"
