name: "Extract configure information for area"

inputs:
  area:
    required: true

outputs:
  area: 
    value: ${{ steps.extract.outputs.area }}

runs:

  using: composite
  steps:

    - name: Extract configure information
      id: extract
      shell: bash
      run: ${{ github.workspace }}/extract-config-info.sh ${{ inputs.area }}
