name: "Extract configure information for area"

inputs:
  area:
    required: true

outputs:
  area: 
    value: ${{ steps.extract.outputs.area }}

runs:

  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependency JQ
      run: |
        sudo apt update
        sudo apt install -y jq

    - name: Extract configure information
      id: extract
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x extract-config-info.sh
        ./extract-config-info.sh "${{ inputs.area }}"
