name: "Extract configure information for area"

inputs:
  area:
    required: true

outputs:
  area: 
    value: ${{ steps.extract.outputs.area }}

runs:

  using: composite
  steps:

    - name: Extract configure information
      id: extract
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        cd ..
        pwd
        ls
        ./extract-config-info.sh ${{ inputs.area }}
