name: "Teste Execucao em matriz"

on:
  issues:
    type: [opened]

jobs: 

  message-starting-process:
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "Starting process ..."

  extracting-area-from-issue:
    runs-on: ubuntu-latest
    outputs:
      area: ${{ steps.extract_area.outputs.area }}
    steps:
      - name: Parsing to Json
        id: parser
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with: 
          issue_id: ${{ github.event.issue.number }}
          separator: "###"
          label_marker_start: ">>"
          label_marker_end: "<<"

      - name: Extract area from payload
        id: extract_area
        run: |
          AREA=$(echo '${{ steps.parser.outputs.payload }}' | jq -r '.Area')
          echo "area=$AREA" >> $GITHUB_OUTPUT

      - name: Print issue body
        run: echo "${{ toJson(steps.parser.outputs.payload) }}"

      - name: Print Area
        run: echo "${{ steps.extract_area.outputs.area }}"

  extracting-file-configuration-information:
    runs-on: ubuntu-latest
    needs: extracting-area-from-issue
    outputs:
      area: ${{ steps.extract.outputs.area }}
      zonas_online: ${{ steps.extract.outputs.zonas_online }}
    steps:
      - name: Extract
        id: extract
        uses: thiagoyuji/teste-actions/.github/actions/extract-config-info@main
        with:
          area: ${{ needs.extracting-area-from-issue.outputs.area }}

  print-information:
    runs-on: ubuntu-latest
    needs: extracting-file-configuration-information
    steps:
      - name: Print information
        run: |
          echo "area: ${{ needs.extracting-file-configuration-information.outputs.area }}"
          echo "zonas_online: ${{ needs.extracting-file-configuration-information.outputs.zonas_online }}"
  
